apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: rohitutekar123/student-api:latest   # ⚠️ change if using DockerHub
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
